"use client";

import { Header } from "@/components/directory/Header";
import { Footer } from "@/components/directory/Footer";

export const DisclaimerView = () => {
  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      <Header />

      <main className="flex-1 py-12 sm:py-16">
        <div className="shell max-w-3xl">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 mb-2">Disclaimer</h1>
          <p className="text-xs text-slate-500 font-medium mb-8">
            Last updated: <time dateTime="2026-07-31">July 31, 2026</time>
          </p>

          <div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm space-y-6 text-xs text-slate-700 font-medium leading-relaxed">
            <section className="space-y-2">
              <h2 className="text-base font-extrabold text-slate-900">General Disclaimer</h2>
              <p>
                The information contained on ModelVault is for general information purposes only. While we endeavor to keep specifications, pricing, hardware requirements, and benchmarks accurate and up to date, we make no representations or warranties of any kind about the completeness, accuracy, reliability, or suitability of the information.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-extrabold text-slate-900">Pricing & API Estimates</h2>
              <p>
                Estimates generated by our cost calculators are based on published list rates from AI model providers. Real-world costs may vary based on caching efficiency, system prompt overhead, tokenization differences, volume discounts, dynamic pricing changes, and region-specific rates. Always verify official billing schedules with provider documentation.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-extrabold text-slate-900">Third-Party Trademarks</h2>
              <p>
                All product names, logos, brands, and registered trademarks belong to their respective holders. Use of third-party names on ModelVault does not imply affiliation or endorsement.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};
